// 3. Refresh token
POST https://localhost:58078/auth/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW5pc3RyYWRvciBkbyBTaXN0ZW1hIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYWRtaW5Ac2doc3MuY29tIiwidW5pZGFkZV9pZCI6Ii0xIiwicHJvZmlzc2lvbmFsX2lkIjoiLTEiLCJwYWNpZW50ZV9pZCI6Ii0xIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImV4cCI6MTc1NjY2Njg2OSwiaXNzIjoiU0dIU1MuQXBpIiwiYXVkIjoiU0dIU1MuQ2xpZW50In0.IeoTpBufk4eHUVGL7ndYEJWDx1yEldQQq3Whh9GLDAk",
    "refreshToken": "o35GcxdHDvS96OjKgTZ2I6rkcWOUBmOFCJOco60+Vn08OxjK6GF3YUGpTOIN6Xe/Wu1SdYAZ0qURVFXVNNne8g=="
}