name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Api Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sghss:${{ github.sha }}
          file: docker/Api.Dockerfile
      - name: Build and push Db Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sghss-db:${{ github.sha }}
          file: docker/Db.Dockerfile
      - name: Run Jenkins pipeline
        env:
          # JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_TOKEN_NAME: ${{ secrets.JENKINS_TOKEN_NAME }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          echo "Running Jenkins pipeline..."
          curl -X POST  https://${{ secrets.JENKINS_URL }}/job/SGHSS_Api/build?token=${{ env.JENKINS_TOKEN }} --user "${{ secrets.JENKINS_USER }}:${{ env.JENKINS_TOKEN }}"
      # - name: Set up Kubernetes credentials
      #   uses: azure/setup-kubectl@v1
      #   with:
      #     version: 'latest'
      #     azure_subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
      #     azure_resource_group: ${{ secrets.AZURE_RESOURCE_GROUP }}
      #     azure_cluster_name: ${{ secrets.AZURE_CLUSTER_NAME }}
      # - name: Deploy to Kubernetes
