name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # This only exists to trigger private builds
    steps:
      - name: Run Jenkins pipeline
        run: |
          echo "Running Jenkins pipeline..."
          curl -X POST  ${{ secrets.JENKINS_URL }}/job/SGHSS_Api/build?token=${{ secrets.JENKINS_TOKEN }} --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}"
